-- IMPORTS
require('core.opts')
require('core.keys')
require('core.color')
require('plugin-setup')
require('plugins.lsp.lspconfig')
require('plugins.lsp.mason')
require('plugins.lsp.rust-tools')
require('plugins.cmp')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.tree')
require('plugins.lualine')
require('plugins.gitsign')
